#!/usr/bin/env python
# -*- coding: utf-8 -*-

import MySQLdb
import pandas as pd
import csv


### 把试听完成的user_id和试听完成时间取出来
### 用pandas读进来
filepath = ("8月试听完成user_end_time.xlsx")
df = pd.read_excel(filepath)

user_id = []
[user_id.append(df['user_id'][k]) for k in range(len(df['user_id']))]
end_time = []
[end_time.append(df['end_time'][k]) for k in range(len(df['end_time']))]

db = MySQLdb.connect(host='',
                     port=,
                     user='',
                     passwd='',
                     db='')
cur = db.cursor()
i = 0
a = list()
for i in range(len(user_id)):
    sql = 'select u.user_id,\
                    u.telephone_num,\
                    sec_to_time(min(c.start_time)-unix_timestamp("{1}")) as "跟进时效",\
                    count(c.start_time) as "跟进次数",\
                    sum(if(c.status = 28, 1, 0)) as "接通次数"\
            from crm_call_outcome_record c\
            left join user_online u on c.customer_number = u.telephone_num\
            where u.user_id = {0}\
            and c.start_time > unix_timestamp("{1}")'.format(user_id[i], end_time[i])

    cur.execute(sql)
    result = cur.fetchall()

    j = 0
    for j in range(len(result)):
        e = 0
        b = list()
        for e in range(len(result[j])):
            b.append(result[j][e])
            print result[j][e],
        a.append(b)
        print len(a), 'rows done'


headers = ['user_id', 'telephone', 'follow_up_efficiency', 'follow_up_times', 'follow_up_talks']
with open('August_finished_preorder_follow_up_details', 'wb') as f:
    f_csv = csv.writer(f)
    f_csv.writerow(headers)
    f_csv.writerows(a)

cur.close()
db.close()
